name: librenms

services:
  db:
    image: mariadb:10
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    env_file:
      - "./env/.env"
    restart: always
    networks:
      - proxy

  redis:
    image: redis:7.2-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    env_file:
      - "./env/.env"
    restart: always
    networks:
      - proxy

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: librenms_msmtpd
    env_file:
      - "./env/.env"
    restart: always
    networks:
      - proxy

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - redis
      - msmtpd
    volumes:
      - "./librenms:/data"
    env_file:
      - "./env/librenms.env"
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librenms.entrypoints=http"
      - "traefik.http.routers.librenms.rule=Host(`librenms.hbnet.co.za`)"
      - "traefik.http.middlewares.librenms-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.librenms.middlewares=librenms-https-redirect"
      - "traefik.http.routers.librenms-secure.entrypoints=https"
      - "traefik.http.routers.librenms-secure.rule=Host(`librenms.hbnet.co.za`)"
      - "traefik.http.routers.librenms-secure.tls=true"
      - "traefik.http.routers.librenms-secure.service=librenms"
      - "traefik.http.services.librenms.loadbalancer.server.port=8000"
      - "traefik.http.routers.librenms-secure.tls.certresolver=cloudflare"
      - "traefik.docker.network=proxy"

  dispatcher:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./env/.env"
    restart: always
    networks:
      - proxy

  syslogng:
    image: librenms/librenms:latest
    container_name: librenms_syslogng
    hostname: librenms-syslogng
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    env_file:
      - "./env/.env"
    restart: always
    networks:
      - proxy

  snmptrapd:
    image: librenms/librenms:latest
    container_name: librenms_snmptrapd
    hostname: librenms-snmptrapd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 162
        published: 162
        protocol: tcp
      - target: 162
        published: 162
        protocol: udp
    volumes:
      - "./librenms:/data"
    env_file:
      - "./env/.env"
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
